---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
install:
  # Install Ansible.
  - sudo pip install 'ansible>2' ansible-lint
  - sudo pip install 
script:
  - ansible --version
  - export ANSIBLE_ROLES_PATH="../"
  - ansible-lint ./
#  - echo localhost > inventory
  - ansible-playbook -i hosts --syntax-check docker.yml
  - ansible-playbook -i hosts --connection=local --sudo -vvvv docker.yml
