- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install make
  apt:
    name: make
    state: present

- name: Install inotify-tools
  apt:
    name: inotify-tools
    state: present

- name: Install net-tools
  apt:
    name: net-tools
    state: present

- name: Install base dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - locales
      - build-essential
      - acl
      - ntp
      - htop
      - git
      - python3-pip
      - libpq-dev
    state: present
  tags:
    - packages

- name: Upgrade pip
  pip:
    name: pip
    state: latest
  tags:
    - packages

- name: "Install Python packages"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - psycopg2-binary

# SETUP NODEJS
- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Add NodeJS deb repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x focal main
    filename: nodesource
    update_cache: true

- name: Add NodeJS deb-src repository
  apt_repository:
    repo: deb-src https://deb.nodesource.com/node_14.x focal main
    filename: nodesource
    update_cache: true

- name: Install NodeJS
  apt:
    name: nodejs
    state: present