---

- hosts: all
  tasks:
    - name: Install the gpg key for nodejs LTS
      become: true
      become_method: sudo
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Add NodeJS deb repository
      become: true
      become_method: sudo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x focal main
        filename: nodesource
        update_cache: true

    - name: Add NodeJS deb-src repository
      become: true
      become_method: sudo
      apt_repository:
        repo: deb-src https://deb.nodesource.com/node_16.x focal main
        filename: nodesource
        update_cache: true

    - name: Install NodeJS
      become: true
      become_method: sudo
      apt:
        name: nodejs
        state: present

    - name: Install make
      become: true
      become_method: sudo
      apt:
        name: make
        state: present

    - name: set dev-address
      become: true
      become_method: sudo
      lineinfile:
        path: /etc/environment
        regexp: '^FASTIFY_ADDRESS='
        insertafter: '^FASTIFY_ADDRESS='
        line: FASTIFY_ADDRESS=0.0.0.0